travis:
  secure:
    BINSTAR_TOKEN: Bd3sOlZxYwQoX6FyVK5OC6use42zo7UZqKrZCcmhPjmkLXXhm3pJHwV4bTkYPi1EsY6o98DLqQvCyzvG5nKlgOxBXWgkY/GovgzLzV1JiVkzL8HARzOdqgk9HWtDFCTy3k5VZzuB0CAXfGu8r82dHToD6ABBQynp+DYZ1LRSHSeOwGLFl+q4sBp6Wc9tHepG6H60wZwVr5bzHLw3IA+UOYVGSJDWqy/qkogneGGBEso7+fPB72AxD7fxidhJd819KKqvGnACX7bNyQmFrlh0QNnoL99uNf4U2wgZnAp54ZYIotERqP7uoJpxmjf0rjOzBf7Du69J+FLCICLoohsz0K5wLnrh3yR2DL6XvSV93cWPOejdT7YKli3/HnkHSJhccCHQNJqA11R1h0S2XBlkZbxKwli3XB/8LavtC8PVju1HBk+ANBSfwUdinkG99iC1NF5hBJbPg3xaKXaz/h/4r8oppvx3Jl/JqcBgaEcVUUxxRQwSdD2FoaZ6MxLWpOoxepy2VssVKlpnrcUwahDJuZQsqwVDkKgkTPbpZt3Ha+Txy4kd/Cykwg1YkFO4gfKXETqB5bZJbOCwxcLBJTcGv7KuaVMPFLVGvvVgHE+N+hyvo0mkIw2yr2dVc7io8R8Nz+2bYddBd42k5Dl0DMdN0nGmPMCMmtcHdsSiE4KFwdk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
